export const BASE_URL = "http://192.168.100.247:3500/api/farmers";
// export const BASE_URL = "http://10.10.30.32:3500/api/farmers";

export const USER_INITIAL_DATA = {
  id: "",
  surname: "",
  firstname: "",
  middlename: "",
  extensionName: "",
  sex: "",
  houseNo: "",
  street: "",
  barangay: "",

  contactNo: "",
  birthDate: null,
  birthPlace: "",
  religion: "",
  specifyReligion: "",
  civilStatus: "",
  spouseName: "",
  motherMaidenName: "",
  householdHead: "",
  householdRelationship: "",
  nameOfHouseholdHead: "",
  numberOfLivingHead: "",
  noMale: "",
  noFemale: "",

  education: "",
  PWD: "",
  _4ps: "",
  memberIndigenousGroup: "",
  specifyIndigenousGroup: "",
  withGovernmentID: "",
  specifyGovernmentID: "",
  idNumber: "",
  memberAssociationOrCooperative: "",
  specifyAssociationOrCooperative: "",
  personToNotifyInCaseEmergency: "",
  contactPersonToNotifyInCaseEmergency: "",

  livelihood: "",
  livestockChecked: false,
  livestockSpecify: "",
  poultryChecked: false,
  poultrySpecify: "",

  landPreparationChecked: false,
  harvestingChecked: false,
  kindOfWorkOther: false,
  kindOfWorkSpecify: "",

  grossAnnualIncome: "",
  specifyGrossAnnualIncome: "",

  specifyGrossAnnualIncome: "",
  idImage: null,
  idImageUri: null,
  userImage: null,
  userImageUri: null,
};

export const BRGY = [
  "Anastacia",
  "Aquino",
  "Ayusan I",
  "Ayusan II",
  "Behia",
  "Bukal",
  "Bula",
  "Bulakin",
  "Cabatang",
  "Cabay",
  "Del Rosario",
  "Lagalag",
  "Lalig",
  "Lumingon",
  "Lusacan",
  "Paiisa",
  "Palagaran",
  "Quipot",
  "San Agustin",
  "San Isidro",
  "San Jose",
  "San Juan",
  "San Pedro",
  "Tagbakin",
  "Talisay",
  "Tamisian",
  "San Francisco",
];
